services:

  customer-service:
    image: customer-service:latest
    ports:
      - "8280:8080"
    depends_on:
      - neo4j
    environment:
      TZ: Asia/Kolkata

  neo4j:
    container_name: neo4j
    image: neo4j:latest
    ports:
      - 7574:7474
      - 7787:7687
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
    volumes:
      - ../../data/customer-service/data:/data
      - ../../data/customer-service/logs:/logs
      - ../../data/customer-service/import:/var/lib/neo4j/import
      - ../../data/customer-service/plugins:/plugins

networks:
  default:
    name: excoder_network